### ISSUE TITLE
Unable to launch sample GA and RS experiment

### ISSUE THREAD

**Issue by andiac** [uber-common/deep-neuroevolution#11]
I have got the following error message when I tried to launch sample GA experiment:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/andi/deep-neuroevolution/es_distributed/main.py", line 90, in <module>
    cli()
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/andi/deep-neuroevolution/es_distributed/main.py", line 84, in workers
    algo.run_worker(master_redis_cfg, relay_redis_cfg, noise=noise)
  File "/home/andi/deep-neuroevolution/es_distributed/ga.py", line 267, in run_worker
    policy, env, task_data.timestep_limit, rs, task_ob_stat, config.calc_obstat_prob)
  File "/home/andi/deep-neuroevolution/es_distributed/ga.py", line 29, in rollout_and_update_ob_stat
    rollout_rews, rollout_len = policy.rollout(env, timestep_limit=timestep_limit, random_stream=rs)
ValueError: too many values to unpack (expected 2)
```
and the following error message when trying to launch sample RS experiment:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/andi/deep-neuroevolution/es_distributed/main.py", line 90, in <module>
    cli()
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andi/deep-neuroevolution/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/andi/deep-neuroevolution/es_distributed/main.py", line 61, in master
    algo.run_master({'unix_socket_path': master_socket_path}, log_dir, exp)
  File "/home/andi/deep-neuroevolution/es_distributed/rs.py", line 52, in run_master
    timestep_limit=tslimit
TypeError: __new__() missing 1 required positional argument: 'ref_batch'
```
Thanks

**Comment by VashishtMadhavan** [comment]
These issues have been fixed in the latest commit [](url)

**Comment by VashishtMadhavan** [comment]
These issues have been fixed in the latest commit 95fc6bd24e865b350c82910efc2be2a0be26a2fd

**Comment by andiac** [comment]
Thanks!

**Comment by Gaoee** [comment]
I test the latest code. But I still got such issue.

This is the error message:
    return callback(*args, **kwargs)
  File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/main.py", line 84, in workers
    algo.run_worker(master_redis_cfg, relay_redis_cfg, noise=noise)
  File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/ga.py", line 230, in run_worker
    eval_rews, eval_length = policy.rollout(env)  # eval rollouts don't obey task_data.timestep_limit
ValueError: too many values to unpack (expected 2)
(env) gaoli@WSGTX1080TI:~/CODE/deep-neuroevolution$ Traceback (most recent call last):
  File "/home/gaoli/tools/Python3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gaoli/tools/Python3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/main.py", line 90, in <module>
    cli()
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/main.py", line 84, in workers
    algo.run_worker(master_redis_cfg, relay_redis_cfg, noise=noise)
  File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/ga.py", line 230, in run_worker
    eval_rews, eval_length = policy.rollout(env)  # eval rollouts don't obey task_data.timestep_limit
ValueError: too many values to unpack (expected 2)

**Comment by EmanueleLM** [comment]
> 
> 
> I test the latest code. But I still got such issue.
> 
> This is the error message:
> return callback(*args, **kwargs)
> File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/main.py", line 84, in workers
> algo.run_worker(master_redis_cfg, relay_redis_cfg, noise=noise)
> File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/ga.py", line 230, in run_worker
> eval_rews, eval_length = policy.rollout(env) # eval rollouts don't obey task_data.timestep_limit
> ValueError: too many values to unpack (expected 2)
> (env) gaoli@WSGTX1080TI:~/CODE/deep-neuroevolution$ Traceback (most recent call last):
> File "/home/gaoli/tools/Python3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/home/gaoli/tools/Python3.6/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/main.py", line 90, in
> cli()
> File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 722, in **call**
> return self.main(*args, **kwargs)
> File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 697, in main
> rv = self.invoke(ctx)
> File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
> return _process_result(sub_ctx.command.invoke(sub_ctx))
> File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 895, in invoke
> return ctx.invoke(self.callback, **ctx.params)
> File "/home/gaoli/CODE/deep-neuroevolution/env/lib/python3.6/site-packages/click/core.py", line 535, in invoke
> return callback(*args, **kwargs)
> File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/main.py", line 84, in workers
> algo.run_worker(master_redis_cfg, relay_redis_cfg, noise=noise)
> File "/home/gaoli/CODE/deep-neuroevolution/es_distributed/ga.py", line 230, in run_worker
> eval_rews, eval_length = policy.rollout(env) # eval rollouts don't obey task_data.timestep_limit
> ValueError: too many values to unpack (expected 2)

it is the same for me on vanilla Ubuntu 18.04 LTS

**Comment by dragon28** [comment]
Hello People,

I am getting the following error when I run . scripts/local_run_exp.sh ga configurations/frostbite_ga.json, which is the GA experiment

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dragon/machine_learning/deep-neuroevolution/es_distributed/main.py", line 90, in <module>
    cli()
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dragon/machine_learning/deep-neuroevolution/es_distributed/main.py", line 84, in workers
    algo.run_worker(master_redis_cfg, relay_redis_cfg, noise=noise)
  File "/home/dragon/machine_learning/deep-neuroevolution/es_distributed/ga.py", line 230, in run_worker
    eval_rews, eval_length = policy.rollout(env)  # eval rollouts don't obey task_data.timestep_limit
```

and I managed to fixed it by changing the following code:

from

deep-neuroevolution/es_distributed/ga.py, line 230:

 `eval_rews, eval_length = policy.rollout(env) # eval rollouts don't obey task_data.timestep_limit`

to:

deep-neuroevolution/es_distributed/ga.py, line 230:

 `eval_rews, eval_length, _ = policy.rollout(env) # eval rollouts don't obey task_data.timestep_limit`

Thanks

**Comment by EmanueleLM** [comment]
Thank you, this solves the problem for me. I appreciate your effort.

Emanuele

________________________________
Da: dragon28 <notifications@github.com>
Inviato: martedì 18 giugno 2019 04:04:19
A: uber-research/deep-neuroevolution
Cc: Emanuele La Malfa; Comment
Oggetto: Re: [uber-research/deep-neuroevolution] Unable to launch sample GA and RS experiment (#11)


Hello People,

I am getting the following error when I run . scripts/local_run_exp.sh ga configurations/frostbite_ga.json, which is the GA experiment

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dragon/machine_learning/deep-neuroevolution/es_distributed/main.py", line 90, in <module>
    cli()
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dragon/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dragon/machine_learning/deep-neuroevolution/es_distributed/main.py", line 84, in workers
    algo.run_worker(master_redis_cfg, relay_redis_cfg, noise=noise)
  File "/home/dragon/machine_learning/deep-neuroevolution/es_distributed/ga.py", line 230, in run_worker
    eval_rews, eval_length = policy.rollout(env)  # eval rollouts don't obey task_data.timestep_limit


and I managed to fixed it by changing the following code:

from

deep-neuroevolution/es_distributed/ga.py, line 230:

eval_rews, eval_length = policy.rollout(env) # eval rollouts don't obey task_data.timestep_limit

to:

deep-neuroevolution/es_distributed/ga.py, line 230:

eval_rews, eval_length, _ = policy.rollout(env) # eval rollouts don't obey task_data.timestep_limit

Thanks

**Comment by Gaoee** [comment]
@EmanueleLM  Thank you. It works.
